#!/bin/sh
set -e

# Map DEV_SUPABASE_* or PROD_SUPABASE_* to REACT_APP_* based on APP_ENV
# This ensures React can access the Supabase credentials

# Create .env.local with React-compatible variable names
cat > /app/.env.local << EOF
# Auto-generated by docker-entrypoint.sh at container start
# Maps Supabase credentials to React environment variables

REACT_APP_SUPABASE_URL=${DEV_SUPABASE_URL}
REACT_APP_SUPABASE_ANON_KEY=${DEV_SUPABASE_ANON_KEY}
REACT_APP_ENV=${REACT_APP_ENV:-development}
REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:3005}
EOF

echo "✅ Frontend environment variables configured"
echo "   REACT_APP_SUPABASE_URL=${DEV_SUPABASE_URL}"

# Execute the main command
exec "$@"
