-- Add AI-powered SEO analysis rules
-- These rules are generated by our lightweight AI content analysis service

DO $$
DECLARE
    seo_module_id UUID;
BEGIN
    -- Get SEO module ID
    SELECT id INTO seo_module_id FROM analysis_modules WHERE name = 'SEO';
    
    -- Insert AI-powered SEO rules
    INSERT INTO rules (module_id, rule_key, name, description, default_severity) VALUES
    (seo_module_id, 'SEO_AI_01_READABILITY', 'Content Readability Issues', 'Content readability score is below recommended threshold for user engagement', 'moderate'),
    (seo_module_id, 'SEO_AI_02_CONTENT_RELEVANCE', 'Content-Title Mismatch', 'Content does not align well with page title and meta description', 'serious'),
    (seo_module_id, 'SEO_AI_03_KEYWORD_RELEVANCE', 'Poor Keyword Integration', 'Target keywords are not well integrated into the content', 'moderate'),
    (seo_module_id, 'SEO_AI_04_CONTENT_GAPS', 'Content Improvement Opportunities', 'AI analysis identified potential content enhancements', 'minor'),
    (seo_module_id, 'SEO_AI_05_SEMANTIC_OPPORTUNITIES', 'Semantic Keyword Opportunities', 'Related semantic keywords could improve content relevance', 'minor')
    ON CONFLICT (rule_key) DO UPDATE SET
        name = EXCLUDED.name,
        description = EXCLUDED.description,
        default_severity = EXCLUDED.default_severity;
        
END $$;